### ISSUE TITLE
Table names with underscores causes error

### ISSUE THREAD

**Issue by siegesmund** [Slava/meteor-rethinkdb#15] opened 2015-05-13 21:33 UTC
Table names with underscores are allowed by RethinkDB, but cause an error on the client side:
![screen shot 2015-05-13 at 5 31 20 pm](https://cloud.githubusercontent.com/assets/2533531/7621605/0c24f16c-f996-11e4-8755-a9d215749950.png)

**Comment by Slava** [comment] 2015-05-23 01:59
Do you have a reproduction code?

**Comment by timstott** [comment] 2015-09-05 23:33
Indeed. This is caused by a bug in reqlite. It was fixed in neumino/reqlite#26.
A [dependency update](https://github.com/Slava/meteor-rethinkdb/blob/de38742fc7d9aeab7a3fa412d7e4387b3aef19b0/driver-source/package.json#L5) is in order, but with the [number of changes](https://github.com/neumino/reqlite/compare/2933b63...master) introduced in reqlite since, it might be bigger job than we think.

**Closed as completed** 2019-11-11 18:45 UTC
